services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 8081:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: